const express = require('express');
const router = express.Router();

// Format analysis into a clean GitHub markdown PR review comment
function formatComment(analysis, prTitle) {
  const riskTable = (analysis.risks || []).length > 0
    ? (analysis.risks || []).map(r =>
        `| ${r.level.toUpperCase()} | ${r.category} | ${r.description} |`
      ).join('\n')
    : '| — | — | No significant risks detected |';

  const reviewerList = (analysis.reviewers || []).length > 0
    ? (analysis.reviewers || []).map(r =>
        `- **@${r.username}** — ${r.reason}`
      ).join('\n')
    : '_No suggestions available._';

  const resourceList = (analysis.resources || []).length > 0
    ? (analysis.resources || []).map(r =>
        r.url ? `- [${r.title}](${r.url}) \`${r.type}\`` : `- ${r.title} \`${r.type}\``
      ).join('\n')
    : '_No linked resources found._';

  return `## 🧭 DevPilot AI Review

### 📝 Summary
${analysis.summary}

---

### ⚠️ Risk Assessment
| Level | Category | Description |
|-------|----------|-------------|
${riskTable}

---

### 🔗 Linked Resources
${resourceList}

---

### 👥 Suggested Reviewers
${reviewerList}

---
<sub>Generated by [DevPilot](https://github.com/Imperiex-1911/devpilot) · Powered by [Airia](https://airia.com) · AI analysis may not be fully accurate — always review manually.</sub>`;
}

router.post('/', async (req, res) => {
  const { owner, repo, prNumber, githubToken, analysis } = req.body;

  if (!owner || !repo || !prNumber || !githubToken || !analysis) {
    return res.status(400).json({ error: 'Missing required fields.' });
  }

  const body = formatComment(analysis);

  try {
    const response = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/issues/${prNumber}/comments`,
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${githubToken}`,
          'Accept': 'application/vnd.github+json',
          'X-GitHub-Api-Version': '2022-11-28',
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ body })
      }
    );

    if (response.status === 401) {
      return res.status(401).json({ error: 'GitHub token is invalid or expired.' });
    }
    if (response.status === 403) {
      return res.status(403).json({ error: 'Insufficient GitHub permissions to post comments.' });
    }
    if (!response.ok) {
      const text = await response.text();
      return res.status(502).json({ error: `GitHub API error ${response.status}: ${text}` });
    }

    const data = await response.json();
    return res.json({ success: true, commentUrl: data.html_url });

  } catch (err) {
    console.error('[comment]', err.message);
    return res.status(500).json({ error: 'Failed to post comment.' });
  }
});

module.exports = router;
