const express = require('express');
const router = express.Router();

router.post('/', async (req, res) => {
  const { slackWebhook, analysis, prTitle, prUrl, owner, repo, prNumber } = req.body;

  if (!slackWebhook || !analysis) {
    return res.status(400).json({ error: 'Missing slackWebhook or analysis.' });
  }

  // Build risk emoji summary
  const riskCounts = { high: 0, medium: 0, low: 0 };
  (analysis.risks || []).forEach(r => {
    if (riskCounts[r.level] !== undefined) riskCounts[r.level]++;
  });

  const riskSummary = [
    riskCounts.high   > 0 ? `🔴 ${riskCounts.high} high`   : null,
    riskCounts.medium > 0 ? `🟡 ${riskCounts.medium} medium` : null,
    riskCounts.low    > 0 ? `🟢 ${riskCounts.low} low`     : null
  ].filter(Boolean).join('  ') || '✅ No risks detected';

  const reviewerMentions = (analysis.reviewers || [])
    .map(r => `@${r.username}`)
    .join(', ') || 'No suggestions';

  const slackPayload = {
    blocks: [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: '🧭 DevPilot PR Analysis',
          emoji: true
        }
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*<${prUrl}|${prTitle || `${owner}/${repo} #${prNumber}`}>*`
        }
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `📝 *Summary*\n${analysis.summary}`
        }
      },
      {
        type: 'section',
        fields: [
          {
            type: 'mrkdwn',
            text: `⚠️ *Risks*\n${riskSummary}`
          },
          {
            type: 'mrkdwn',
            text: `👥 *Suggested Reviewers*\n${reviewerMentions}`
          }
        ]
      },
      {
        type: 'actions',
        elements: [
          {
            type: 'button',
            text: { type: 'plain_text', text: 'View PR', emoji: true },
            url: prUrl,
            style: 'primary'
          }
        ]
      },
      {
        type: 'context',
        elements: [
          {
            type: 'mrkdwn',
            text: 'Generated by *DevPilot* · Powered by Airia'
          }
        ]
      }
    ]
  };

  try {
    const response = await fetch(slackWebhook, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(slackPayload)
    });

    if (!response.ok) {
      const text = await response.text();
      return res.status(502).json({ error: `Slack webhook error: ${text}` });
    }

    return res.json({ success: true });

  } catch (err) {
    console.error('[notify]', err.message);
    return res.status(500).json({ error: 'Failed to send Slack notification.' });
  }
});

module.exports = router;
